### ISSUE TITLE
deprecated --dev option and first taskfile.yaml without uppercase

### ISSUE THREAD

**Issue by adnene-guessoum** [Tea-n-Tech/professional-python#4]
(I'm mainly opening an issue to see how it's done)

playing around in the third lesson on linting and formatting, I got a warning saying that "--dev" is deprecated and to use : 
"poetry add flake9 pylint --group dev "

also the first taskfile.yaml must be written with an uppercase "Taskfile.yaml" which wasn't mentionned in the beginning of the README (it is after however). 

Thx for the lessons :)

**Comment by codie3611** [comment]
Thanks for the feedback :heart:
